# Site settings
locale: "it-IT"
title: DevCode
title_separator: "-"
email: info@devcode.it
description: "Documentazione del gestionale open-source OpenSTAManager"
baseurl: ""
url: "https://devcode-it.github.io"
github_username: "devcode-it"
repository: "devcode-it/devcode-it.github.io"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

docs-version: 2.4.2

collections:
  openstamanager:
    output: true
    permalink: /:collection/2.4.2/:path/

# Defaults
defaults:
  # _openstamanager
  - scope:
      path: ""
      type: openstamanager
    values:
      layout: single
      toc: true
      read_time: true
      pagination: false
      sidebar:
        nav: "guide-sidebar"
      navigation:
        nav: "osm-menu"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: UA-42808312-1
    anonymize_ip: false

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']