# Site settings
locale: "it-IT"
title: OpenSTAManager
title_separator: "-"
email: info@devcode.it
description: "Documentazione del gestionale open-source OpenSTAManager"
baseurl: ""
url: "https://devcode-it.github.io"
github_username: "devcode-it"
repository: "devcode-it/devcode-it.github.io"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

docs-version: 2.4.6

collections:
  openstamanager:
    output: true
    permalink: /:collection/2.4.6/:path/

# Defaults
defaults:
  # _openstamanager
  - scope:
      path: ""
      type: openstamanager
    values:
      layout: single
      toc: true
      read_time: true
      pagination: false
      sidebar:
        nav: "guide-sidebar"
      navigation:
        nav: "osm-menu"

# Footer
footer:
  links:
    - label: "Sito ufficiale"
      icon: "fas fa-external-link-alt"
      url: "https://www.openstamanager.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/openstamanager"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devcode-it/openstamanager"
    - label: "Forum"
      icon: "fas fa-comments"
      url: "https://www.openstamanager.com/forum"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: UA-42808312-1
    anonymize_ip: false

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-relative-links
  - jekyll-include-cache

relative_links:
  enabled: true
  collections: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
